import 'dart:io';

import 'package:args/command_runner.dart';
import 'package:flutter_smartgen/src/config/smartgen_config.dart';
import 'package:flutter_smartgen/src/utils/project_root.dart';
import 'package:path/path.dart' as p;

/// Creates smartgen.yaml in the target Flutter project.
class InitCommand extends Command<int> {
  @override
  String get name => 'init';

  @override
  String get description => 'Create smartgen.yaml in the current Flutter project.';

  @override
  Future<int> run() async {
    final ProjectRoot root = ProjectRoot.find();
    final File configFile = File(
      p.join(root.directory.path, SmartgenConfig.fileName),
    );

    if (configFile.existsSync()) {
      stdout.writeln(
        '${SmartgenConfig.fileName} already exists at ${configFile.path} — skipped.',
      );
      return 0;
    }

    final String packageName = root.readPackageName();
    final String content = buildDefaultYaml(packageName);

    configFile.writeAsStringSync(content);
    stdout.writeln('Created ${configFile.path}');
    stdout.writeln('package_name: $packageName (from pubspec.yaml)');
    stdout.writeln(
      'Optional: add common_scaffold under smartgen.yaml if your app uses a shared scaffold widget.',
    );
    return 0;
  }

  /// Default smartgen.yaml content for [packageName].
  static String buildDefaultYaml(String packageName) {
    return '''
# Generated by smartgen init — package_name comes from pubspec.yaml
package_name: $packageName
screens_base: lib/screens

# Optional: uncomment and set paths to use CommonScaffold instead of Scaffold
# common_scaffold:
#   import: package:$packageName/widgets/common_scaffold.dart
#   class_name: CommonScaffold

naming:
  screen_suffix: Screen
  controller_suffix: Controller

assets:
  images:
    output: lib/app/app_images.dart
    class_name: AppImages
    directories:
      - assets/images
      # - assets/icons
''';
  }
}
