/// String templates for generated environment files.
class EnvTemplates {
  /// Content for `.env.development` and `.env.production`.
  static String envFileContent() {
    return '''
# Generated by smartgen env — add real values locally; do not commit secrets.
BASE_URL=
API_KEY=
''';
  }
}
